name: tests
on:
  pull_request:
  push:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.2"
          cache-dependency-path: "**/go.sum"
      - name: Run the tests
        run: make run-tests
